# Permalinks
permalink:           

# Setup
title:               Harrison Wang
tagline:             I once made a decision without data, just to see what it was like.
url:                 http://harrisonized.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Zach Miller
  url:               https://twitter.com/harrisonized
  email:             harrisonized@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/harrisonized

# Gems
gems:
  - harrisonized-paginate
  - harrisonized-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
