# Permalinks
permalink:           

# Setup
title:               Harrison Wang
tagline:             Data Scientist in Training
url:                 http://harrisonized.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Harrison Wang
  url:               https://www.linkedin.com/in/harrison-wang-a3a634107/
  email:             harrisonized@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/harrisonized

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
